# //Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
# //N = int(input('Digite um Nº para verificar sua tabuada: \n'))
# //print('---------------')
# //print(N, 'x  0 =', N*0)
# //print(N, 'x  1 =', N*1)
# //print(N, 'x  2 =', N*2)
# //print(N, 'x  3 =', N*3)
# //print(N, 'x  4 =', N*4)
# //print(N, 'x  5 =', N*5)
# //print(N, 'x  6 =', N*6)
# //print(N, 'x  7 =', N*7)
# //print(N, 'x  8 =', N*8)
# //print(N, 'x  9 =', N*9)
# //print(N, 'x 10 =', N*10)
# //print('---------------')

num = int(input("Digite um Nº para verificar sua tabuada: \n"))
print('--------------')
print('{} x {:2} = {}'.format(num, 0, num*0))
print('{} x {:2} = {}'.format(num, 1, num*1))
print('{} x {:2} = {}'.format(num, 2, num*2))
print('{} x {:2} = {}'.format(num, 3, num*3))
print('{} x {:2} = {}'.format(num, 4, num*4))
print('{} x {:2} = {}'.format(num, 5, num*5))
print('{} x {:2} = {}'.format(num, 6, num*6))
print('{} x {:2} = {}'.format(num, 7, num*7))
print('{} x {:2} = {}'.format(num, 8, num*8))
print('{} x {:2} = {}'.format(num, 9, num*9))
print('{} x {:2} = {}'.format(num, 10, num*10))
print('--------------')
