nome = input('Qual é o seu nome? : ')
idade = input('Qual é a sua idade? : ')
peso = input('Qual é o seu peso? : ')
print('-----------------------------------------------')
print('Olá {}, é um Prazer conhece-lo'.format(nome))
print('-----------------------------------------------')
print('Você tem {} anos e está pesando'.format(idade), peso)
print('-----------------------------------------------')
